### ISSUE TITLE
Where to download the images in the dataset?

### ISSUE THREAD

**Issue by YeeHoran** [AmirSh15/FECNet#7]
There is only csv files for test and train dataset, but without the images mentioned in the csv. 

Could you send me the link where to download the overall images, please?

Thank you!

**Comment by AmirSh15** [comment]
Hi,

You must first fill out a form here (https://research.google/tools/datasets/google-facial-expression/) to access the data. Later on, they will send the access email to you.

**Comment by YeeHoran** [comment]
Thank you for your suggestion! However, after I filled out the form, there isn't further request for my email address to send me the dataset!

In addition, I met another problem when I run the code, and the error is the following:

Number of Trainable Parameters= 2919312
Traceback (most recent call last):

  File "/home/yi/anaconda3/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/yi/Documents/1. Research/3. public code/A-compact-embedding-for-facial-expression-similarity-main/FECNet 20221009.py", line 97, in <module>
    for i_batch, sample_batched in enumerate(tr_dataloader):

  File "/home/yi/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 683, in __next__
    data = self._next_data()

  File "/home/yi/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1378, in _next_data
    return self._process_data(data)

  File "/home/yi/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1404, in _process_data
    data.reraise()

  File "/home/yi/anaconda3/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yi/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yi/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yi/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yi/Documents/1. Research/3. public code/A-compact-embedding-for-facial-expression-similarity-main/utils/data_prep.py", line 40, in __getitem__
    image_1 = cv2.imread(data.iloc[id, 1])
TypeError: Can't convert object of type 'numpy.float64' to 'str' for 'filename'

I have tried to debug the error for nearly 2 weeks, but still can't figure out the problem point. Could you tell me the reason, please? I'll appreciate your support very much!

Thank you again!

YeeHoran

**Comment by AmirSh15** [comment]
Hi Yee,

The processing and giving access might take a few days!

For your error, it seems that the CSV file you used as an input to the [dataloader](https://github.com/AmirSh15/FECNet/blob/e624693bd638478c55c0d4c6ec86c4e3b9fbe9d0/FECNet.py#L81) is not consistence with the code; it expects to see an image address as a string (data.iloc[id, 1]) but you gave a float number. Could you please tell me, how did you prepare the input CSV file?

**Comment by YeeHoran** [comment]
Thank you so much for your help! @AmirSh15 

The way I got the csv file is as follows:

First, I open the website  https://research.google/tools/datasets/google-facial-expression/, whose UI is as follows:
<img width="1440" alt="Screen Shot 2022-10-16 at 9 08 04 PM" src="https://user-images.githubusercontent.com/72056465/196037542-94ee9d4c-0d69-4253-8f12-1ac7204cd394.png">

Then, a form appeared for me to fill it out, whose UI is as follows:
<img width="1440" alt="Screen Shot 2022-10-16 at 9 22 40 PM" src="https://user-images.githubusercontent.com/72056465/196037908-2e76dc8c-d367-4da0-a768-83adc7f4eaba.png">

After I submitted the form, it redirected to a URL for downloading dataset and the UI is as follows:
<img width="1440" alt="Screen Shot 2022-10-16 at 9 26 19 PM" src="https://user-images.githubusercontent.com/72056465/196038008-8d92fadf-61aa-408e-a4c7-dddacd6b25ae.png">

Next, I download the "FEC_dataset.zip" file from the above download link. The zip file is too large to upload here, and the unzipped files's snapshot are as follows:
![image](https://user-images.githubusercontent.com/72056465/196038261-8f2f520e-2a19-4fd8-a7ea-2f628f19b7d6.png)

Finally, The screenshot of  "faceexp-comparison-data-train-public.csv" is as follows:
<img width="1440" alt="Screen Shot 2022-10-16 at 9 34 37 PM" src="https://user-images.githubusercontent.com/72056465/196038649-ea682fff-5145-4747-b4d0-2d5cf8da8c74.png">


On the other side, I have tried many times filling out the form in different days, but there isn't any response about the image files of the dataset. 

I appreciate your kind support very much and looking forward to your reply!

Sincerely, 

Yee Horan

**Comment by AmirSh15** [comment]
Hi Yee,

Thanks for your detailed response. These are the files you need to run the code. Don't ask for more!
The 'faceexp-comparison-data-train-public.csv' file contains the download link of the images you need for training. [Here](https://github.com/AmirSh15/FECNet/blob/e624693bd638478c55c0d4c6ec86c4e3b9fbe9d0/FECNet.py#L58) in the main code will download images. You can check the downloaded images in 'data/train'.
Could you please check 'data/labels.csv' exists and print the contents?

**Comment by AmirSh15** [comment]
Hi Yee,

That's fine! The 'faceexp-comparison-data-train-public.csv' contents seem alright. Could you please check that the code downloads (here 'data/train') the images and creates the label.csv (here 'data/labels.csv')

**Comment by YeeHoran** [comment]
Dear Amir,

Thank you for your suggestion and I'll check the connection issue next.

Now, when I tried to debug it to the breakpoint line that is highlighted in red on the left side in the following picture, it stuck in the condition that is highlighted in green on the right side. This lasts for more than 12 hours, and nothing happened but this.
![image](https://user-images.githubusercontent.com/72056465/196306765-bca6d635-8742-45e5-89cd-9d17c010dfd8.png)

Could you tell me why this happened and is it in normal status, please? 

Thank you very much and I'm looking forward to your reply!

Sincerely,

Yee Horan

**Comment by AmirSh15** [comment]
Hi Yee,

I think this error happens when your images don't exist in the expected path, or at least some of them. Did you download all the images?

**Comment by YeeHoran** [comment]
Dear Amir,

No, I tried to download the images many times for a whole day, but every time only these 18 images could be downloaded, as the following print shows:
![Screenshot from 2022-10-18 21-30-36](https://user-images.githubusercontent.com/72056465/196446111-86ee1744-3e80-4908-9d90-8a86d99fcd21.png)

**Comment by YeeHoran** [comment]
Dear Amir,

I debugged the code today, and found something that may cause the problem of very few downloaded images.

I enter the download_image() (line129) function in 'image_downloader.py', it runs correctly from line130 to line 139, which analyze the 'label.csv' into 8 dictionaries with items of image url and its cropped coordinates, and create 8 get image threads from t1 to t8 as well.

However, from line141, when threads start() with such as 't1.start()' that begin to download images, problems arise as follows,

Take t1.start() as an example, other threads come across the same problem.

There are 39173 image URLs in name_dic1 which t1 could use to download, crop and same new sample images, but only two image URLs are processed by t1, because only these two URLs are printed on the console: as the following screenshot shows, the print(key) line that prints out the the image URL to access and the printed out URLs that only be processed by t1 are highlighted by green circle.
![image](https://user-images.githubusercontent.com/72056465/197148285-c3beac91-d255-4fb6-92d1-6ee03ee85717.png)

But, all the other image URLs except the above two could really be accessed by browser, and I tried a lot them. So, for t1 and other threads from t2 to t8, only the printed image URLs printed out on the console are processed by the thread, and most of them are never processed at all.

I tried to enter the _start_new_thread() function in line 892 located in 'threading.py', but it didn't enter at all but run to the following lines directly.
![Screenshot from 2022-10-21 16-24-21 copy](https://user-images.githubusercontent.com/72056465/197149853-bbb8f5ff-bc8c-4743-a4b6-1c6469cd6802.png)

So, these are all I found today, and in a word, I think most of the image URLs are not processed at all, and only very few of them are processed. But I can't find out the reason. I hope you could initiate debugging it, and that will favor and speed up my research a lot!

Thank you for your support again!

Best regards,

Yee Horan

**Comment by AmirSh15** [comment]
Hi Yee,

I updated the code. Please check and let me know if you have any difficulties.

**Comment by YeeHoran** [comment]
Dear Amir,

Thank you so much for your time and work to update the code so quickly! I'll run it at once.

**Comment by YeeHoran** [comment]
Dear Amir, 

I run the preprocess.py code, in which download_image() is carried out. I run it 5 times, and the numbers of downloaded images into 'data/train' path are 888, 890, 866, 897, 888. In addition, each time it stuck when downloading the same file named 'http://farm8.staticflickr.com/7377/10177367366_9279901900_b.jpg' whose last location in 'faceexp-comparison-data-train-public.csv' is row 435140 that near the end, and is shown as follows,
![Screenshot from 2022-10-25 13-34-00](https://user-images.githubusercontent.com/72056465/197692164-b1b25b02-64cd-4d79-9998-b2b82ffff283.png)
![Screenshot from 2022-10-25 13-15-57](https://user-images.githubusercontent.com/72056465/197692183-df9161cd-1f8f-4183-80f7-6fffb1729633.png)

I have no idea why only about 900 images were downloaded at each time, and why it is always the same file that seems to cause download error and stop the program running.

Thank you so much for your consistent help and support and I am looking forward to your reply!

Best regards,

Yee Horan

**Comment by AmirSh15** [comment]
Hi Yee,
It's weird because I ran the code without any problem. Could you please post your error?

**Comment by YeeHoran** [comment]
Dear Amir,

Thank you for your quick reply!

The errors shown in the console are like this:

![Screenshot from 2022-10-26 06-42-04](https://user-images.githubusercontent.com/72056465/197902434-8b637609-00d6-499a-8a62-16f1179abed6.png)
![Screenshot from 2022-10-26 06-42-12](https://user-images.githubusercontent.com/72056465/197902562-81bd0189-54a9-4a21-b70b-d98185bef160.png)
![Screenshot from 2022-10-26 06-42-25](https://user-images.githubusercontent.com/72056465/197902669-d3e305fd-2fbb-4713-afa9-c128dee4e3c8.png)
![Screenshot from 2022-10-26 06-42-32](https://user-images.githubusercontent.com/72056465/197904365-863384eb-a06c-4b9c-98b2-c45e97626b15.png)

Additionally, I tried to access the file 'https://farm8.staticflickr.com/7377/10177367366_9279901900_b.jpg' from browser directly, but the result is like this:
![Untitled](https://user-images.githubusercontent.com/72056465/197904774-fc926b2e-4b9a-411c-9d4f-07a0bde3f0f9.png)

So, do you know the reason why it always carried out in this way, please? 

Thank you very much for your time and support!

**Comment by AmirSh15** [comment]
Hi Yee,

I'm sure that this is something related to your internet provider. I tried again today, and everything is running smoothly.

**Comment by YeeHoran** [comment]
Dear Amir,

Thank you very much for your time and support on this!

I'll check my internet connection to solve it .

Thank you again for your consistent support!

**Comment by anonydeven** [comment]
Hi, @YeeHoran Were you able to download all the images? I am also having the same issue.

**Comment by YeeHoran** [comment]
Hi, @anonydeven  #8 has the links to download the image, which is also presented as follows:
[https://research.google/tools/datasets/google-facial-expression/](url)

Hope this help you!

**Comment by anonydeven** [comment]
@YeeHoran Yes, I did follow the links and EULA agreement but I am able to download 70K images only. The rest says "Not Complete Image ...". 
Were you able to download the complete dataset?
